language: java
jdk:
  - oraclejdk8
sudo: true
cache:
  apt: true
  directories:
    - $HOME/.m2
addons:
  apt:
    sources:
    - rabbitmq-testing
    packages:
    - rabbitmq-server
script:
  - mvn -Drod.build.env=travis clean install jacoco:report coveralls:report
